---
- name: Converge
  hosts: all
  roles:
    - role: "{{ lookup('env', 'PWD') | basename }}"
  post_tasks:
    - name: dump
      changed_when: false
      copy:
        content: "{{ vars | to_yaml }}"
        dest: /tmp/ansible-vars.yml
