---
- name: Generate dhparams for nginx
  include_role:
    name: veselahouba.letsencrypt
  vars:
    letsencrypt_cert_list: []

- name: Run Let'sencrypt tasks for {{ zammad_instance.name }}
  include_role:
    name: veselahouba.letsencrypt
  vars:
    letsencrypt_cert_list:
      - name: "{{ zammad_instance.zammad_fqdn }}"
        mail: "{{ zammad_instance.letsencrypt_email|default(letsencrypt_email) }}"
        state: "{{ zammad_instance.state|d('present') }}"
  when: zammad_instance.letsencrypt_deploy | default(true)

- name: Run nginx tasks {{ zammad_instance.name }}
  include_role:
    name: veselahouba.nginx
  vars:
    nginx_sites: "{{
      {
        zammad_instance.zammad_fqdn:
        {
          'template': 'nginx-proxy-zammad.conf.j2',
          'passed_item': zammad_instance
        }
      }
    }}"
    nginx_configs:
      zammad_logs:
        - >
          log_format zammad
          '$remote_addr - $remote_user
          [$time_local] "$request" $status $body_bytes_sent
          "$http_referer" "$http_user_agent"
          "$http_x_forwarded_for"
          rt=$request_time urt=$upstream_response_time';
