---
- name: Run nginx tasks
  include_role:
    name: jdauphant.nginx
  vars:
    nginx_sites: "{{
      {
        zammad_instance.zammad_fqdn:
        {
          'template': 'nginx-proxy-zammad.conf.j2',
          'passed_item': zammad_instance
        }
      }
    }}"

- name: Run Let'sencrypt tasks
  include_role:
    name: veselahouba.letsencrypt
  vars:
    ssl_certs_letsencrypt_list:
      - name: "{{ zammad_instance.zammad_fqdn }}"
        mail: support@lcx.at
        state: "{{ zammad_instance.state|d(omit) }}"
  when: zammad_instance.letsencrypt_deploy | default(true)
