---
- name: Make sure git is installed
  apt:
    name: git

- name: Prepare zammad git repos for deploy
  git:
    dest: "/opt/docker/{{ zammad_instance.name }}"
    repo: "https://github.com/zammad/zammad-docker-compose.git"
    version: master
    update: false

- name: Custom docker-compose overrides
  template:
    src: docker-compose.override.yml.j2
    dest: "/opt/docker/{{ zammad_instance.name }}/docker-compose.override.yml"
    mode: 0644
    owner: root
    group: root

- name: Grafana config
  copy:
    src: grafana/
    dest: "/opt/docker/{{ zammad_instance.name }}/grafana/"
    mode: 0644
    directory_mode: 0755
    owner: root
    group: root
  when: zammad_instance.grafana_port is defined

- name: Deploy docker
  include_role:
    name: veselahouba.docker

- name: Apply pending tasks
  meta: flush_handlers

- name: Deploy docker
  include_role:
    name: veselahouba.docker_container
  vars:
    docker_composes:
      - name: "{{ zammad_instance.name }}"
        project_src: /opt/docker/{{ zammad_instance.name }}
        state: "{{ zammad_instance.state|default('present') }}"

- name: Wait for zammad instance to start
  uri:
    url: "http://localhost:{{ zammad_instance.zammad_custom_port }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
