---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}
    server_type: cx11
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        zammad_instances:
          - name: zammad-test
            zammad_custom_port: 10080
            zammad_nginx_container_port: 8080
            zammad_fqdn: your_fqdn
            zammad_backend_ip: 127.0.0.1
            proxy_server: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}
            docker_server: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}
            custom_cert: /etc/ssl/certs/ssl-cert-snakeoil.pem
            custom_cert_key: /etc/ssl/private/ssl-cert-snakeoil.key
            grafana_port: 3000
            letsencrypt_deploy: false
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
