{
 "title": "Zammad: Caller Stats",
 "description": "Sample Dashboard for displaying CTI-Log Statistics of your Zammad instance.",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval_graphs", "label": "Graph Intervall", "query": "1h,1d,2d,7d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Number of calls by direction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "calls" } },
   "targets": [
    {
     "alias": "incoming",
     "bucketAggs": [
      {
       "id": "2",
       "settings": {
        "filters": [
         { "label": "", "query": "direction.keyword: in" }
        ]
       },
       "type": "filters"
      },
      { "field": "created_at", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "done: true",
     "timeField": "start_at"
    },
    {
     "alias": "outgoing",
     "bucketAggs": [
      {
       "id": "4",
       "settings": {
        "filters": [
         { "label": "", "query": "direction.keyword: out" }
        ]
       },
       "type": "filters"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "done: true",
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Call Ratio incoming / outgoing",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "calls" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "direction.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Average waiting time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "duration_waiting_time_s",
     "bucketAggs": [
      { "field": "end_at", "id": "3", "settings": { "interval": "1h", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration_waiting_time", "id": "1", "type": "avg" }
     ],
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Average talking time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "duration_talking_time_s",
     "bucketAggs": [
      { "field": "created_at", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration_talking_time", "id": "1", "type": "avg" }
     ],
     "query": "done: true",
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Top 10 callers (in)",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "from.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "direction: in",
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Top 10 answerers (in)",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "to.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "direction: in",
     "timeField": "start_at"
    }
   ]
  }
 ]
}