{
 "title": "Zammad: Chats",
 "description": "Sample Dashboard for displaying Chat Statistics of your Zammad instance. Features chat origins, topic ratios and other Metas.",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval_graphs", "label": "Graph Intervall", "query": "1h,1d,2d,7d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Chat Sessions per day",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Chatting countries (origin)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "preferences.geo_ip.country_code.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 Chat tags",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tags.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 Chat agents",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user.login.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 Chat exit pages",
   "type": "table",
   "description": "This is the last page the chat was used on. If the user browses the website, the URL may change.",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "preferences.url.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 City origins",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "preferences.geo_ip.city_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Average number of messages",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Messages" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "created_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "messages.id", "id": "1", "type": "cardinality" }
     ],
     "query": "state: \"closed\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Chat topic ratio",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "chat.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      { "field": "created_at", "id": "4", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Average chatting time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "updated_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "state: \"closed\"",
     "timeField": "created_at"
    },
    {
     "bucketAggs": [
      {
       "field": "id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "created_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "state: \"closed\"",
     "timeField": "created_at"
    }
   ]
  }
 ]
}